export default function getAllGadgets() {
  return [
    {
      id: "GPH-13-APL-001",
      slug: "iphone-13-pro",
      name: "iPhone 13 Pro",
      category: `Smartphone`,
      categorySlug: "smartphone",
      price: 18_499_000,
      stock: 4,
      imageUrl: "/assets/images/IP13pro.jpg",
      description: `The iPhone 13 Pro features an advanced triple-camera system, A15 Bionic chip, and ProMotion technology for a super smooth experience.`,
    },
    {
      id: "GPH-16-APL-013",
      slug: "iphone-16-pro-max",
      name: "iPhone 16 Pro Max",
      category: `Smartphone`,
      categorySlug: "smartphone",
      price: 30_999_000,
      stock: 12,
      imageUrl: "/assets/images/IP16.jpg",
      description: `The iPhone 16 Pro Max features an A18 Bionic chip, advanced triple-camera system, and Dynamic Island 2.0 for the ultimate iOS experience.`,
    },
    {
      id: "LPT-ROG-X16-014",
      slug: "asus-rog-flow-x16",
      name: "ASUS ROG Flow X16",
      category: `Laptop`,
      categorySlug: "laptop",
      price: 42_999_000,
      stock: 0,
      imageUrl: "/assets/images/ROGX16.jpg",
      description: `ASUS ROG Flow X16 delivers exceptional gaming performance with an AMD Ryzen 9 processor and RTX 4080 graphics in a convertible design.`,
    },
    {
      id: "TAB-S9-GLX-015",
      slug: "samsung-galaxy-tab-s9-ultra",
      name: "Samsung Galaxy Tab S9 Ultra",
      category: `Tablet`,
      categorySlug: "tablet",
      price: 18_499_000,
      stock: 15,
      imageUrl: "/assets/images/TabS9.jpg",
      description: `The Galaxy Tab S9 Ultra offers a massive 14.6-inch AMOLED display and the latest Snapdragon processor for immersive productivity and entertainment.`,
    },
    {
      id: "AUD-SNY-XM5-016",
      slug: "sony-wh-1000xm5",
      name: "Sony WH-1000XM5",
      category: `Audio`,
      categorySlug: "audio",
      price: 6_999_000,
      stock: 0,
      imageUrl: "/assets/images/Sonyxm5.webp",
      description: `Sony WH-1000XM6 provides industry-leading noise cancellation and superior audio quality for music and calls, perfect for travel and daily use.`,
    },
    {
      id: "GPH-PXL-9P-017",
      slug: "google-pixel-9-pro",
      name: "Google Pixel 9 Pro",
      category: `Smartphone`,
      categorySlug: "smartphone",
      price: 19_499_000,
      stock: 5,
      imageUrl: "/assets/images/Google Pixel 9 Pro.jpg",
      description: `Google Pixel 9 Pro features an advanced Tensor G3 chip, enhanced AI camera capabilities, and Android 15 for a seamless user experience.`,
    },
    {
      id: "LPT-MBA-M5-018",
      slug: "macbook-pro-m3",
      name: "MacBook Pro M3",
      category: `Laptop`,
      categorySlug: "laptop",
      price: 35_999_000,
      stock: 10,
      imageUrl: "/assets/images/m3pro.webp",
      description: `MacBook Air M5 combines power and portability with Apple's latest M5 chip and a stunning Liquid Retina XDR display.`,
    },
    {
      id: "AUD-BSE-QCU-019",
      slug: "bose-quietcomfort-ultra",
      name: "Bose QuietComfort Ultra Earbuds",
      category: `Audio`,
      categorySlug: "audio",
      price: 4_999_000,
      stock: 25,
      imageUrl: "/assets/images/Bose QuietComfort Ultra Earbuds.jpg",
      description: `Bose QuietComfort Ultra Earbuds deliver world-class noise cancellation, stunning sound quality, and all-day comfort for music lovers.`,
    },
  ];
}
